# This is a basic workflow for linting and formatting checks, as well as running tests
name: app-linter-and-tester

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "lintAndTest"
  lintAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1
      # install dependencies
      - name: Install dependencies 
        run: npm install
      # linting and formatting checks
      - name: Run Format
        run: npm run format
      - name: Run Lint
        run: npm run lint
      # linting and formatting checks
      - name: Run Tests
        run: npm test --prefix backend